// EXERCISE 1
// QUESTION-- YOU HAVE TO CREATE A VARIABLE WHICH IS A STRING CONTAINING THE TEST WHICH IS A LINK YOU ARE INTERESTED IN.

// YOU HAVE TO FETCH ALL THE LINKS FROM A GOVEN PAGE WHCH CONTAINSS THIS TEXT

// EXMAMPLE- WEBSITE= Codewithharry and VARIABLE= javascript.

